### ISSUE TITLE
Error when start

### ISSUE THREAD

**Issue by DekaSKy** [Splash-07/fw-bot#11]
C:\Users\Devos\Desktop\fw-bot-main>npm i

up to date, audited 1502 packages in 2s

174 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (6 moderate, 2 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

C:\Users\Devos\Desktop\fw-bot-main>npm start

> farmersworld@2.0.3 start
> react-scripts start

(node:13692) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:13692) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...
Compiled with warnings.

Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-api-interfaces.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-api-interfaces.ts'
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-api.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-api.ts'

Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-jsonrpc.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-jsonrpc.ts'

Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-numeric.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-numeric.ts'

Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-rpc-interfaces.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-rpc-interfaces.ts'
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-rpcerror.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-rpcerror.ts'

Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-serialize.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-serialize.ts'

Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\index.ts'

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

assets by path static/media/*.woff2 1.45 MiB
  asset static/media/m-plus-rounded-1c-55-400-normal.847a33d1080b0da9037b.woff2 28.6 KiB [emitted] [immutable] [from: node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-55-400-normal.woff2] (auxiliary name: main)
  asset static/media/m-plus-rounded-1c-35-400-normal.03f5f8073aee3d98f730.woff2 18.7 KiB [emitted] [immutable] [from: node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-35-400-normal.woff2] (auxiliary name: main)
  asset static/media/m-plus-rounded-1c-119-400-normal.1112fdbac4e08271ddaa.woff2 17.9 KiB [emitted] [immutable] [from: node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-119-400-normal.woff2] (auxiliary name: main)
  + 115 assets
assets by path static/media/*.png 406 KiB
  asset static/media/corn-icon.7bb4084f19e83a4022eb.png 139 KiB [emitted] [immutable] [from: src/assets/icons/corn-icon.png] (auxiliary name: main)
  asset static/media/egg-icon.c0fd1324cf8f1c327ca3.png 107 KiB [emitted] [immutable] [from: src/assets/icons/egg-icon.png] (auxiliary name: main)
  asset static/media/barley-icon.18ec6ddbda09e9d44fc0.png 72 KiB [emitted] [immutable] [from: src/assets/icons/barley-icon.png] (auxiliary name: main)
  asset static/media/milk-icon.b29da81d6d2c2ae0f023.png 48.2 KiB [emitted] [immutable] [from: src/assets/icons/milk-icon.png] (auxiliary name: main)
  asset static/media/coin-icon.989412b1359df143dd01.png 40.6 KiB [emitted] [immutable] [from: src/assets/icons/coin-icon.png] (auxiliary name: main)
asset static/js/bundle.js 5.05 MiB [emitted] (name: main) 1 related asset
asset static/media/m-plus-rounded-1c-all-400-normal.5113712554d9c327d5df.woff 1.47 MiB [emitted] [immutable] [from: node_modules/@fontsource/m-plus-rounded-1c/files/m-plus-rounded-1c-all-400-normal.woff] (auxiliary name: main)
asset asset-manifest.json 16.2 KiB [emitted]
asset index.html 588 bytes [emitted]
cached modules 4.06 MiB (javascript) 3.32 MiB (asset) 29.7 KiB (runtime) [cached] 880 modules

WARNING in ./node_modules/eosjs/dist/eosjs-api-interfaces.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-api-interfaces.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-api-interfaces.ts' @ ./node_modules/eosjs/dist/index.js 17:20-53
 @ ./src/service/wax.ts 4:0-32 13:21-28 65:12-19
 @ ./src/components/Home.tsx 16:0-39 34:15-20
 @ ./src/App.tsx 6:0-37 38:39-43
 @ ./src/index.tsx 6:0-24 19:37-40

WARNING in ./node_modules/eosjs/dist/eosjs-api.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-api.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-api.ts'
 @ ./node_modules/eosjs/dist/index.js 8:18-40
 @ ./src/service/wax.ts 4:0-32 13:21-28 65:12-19
 @ ./src/components/Home.tsx 16:0-39 34:15-20
 @ ./src/App.tsx 6:0-37 38:39-43
 @ ./src/index.tsx 6:0-24 19:37-40

WARNING in ./node_modules/eosjs/dist/eosjs-jsonrpc.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-jsonrpc.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-jsonrpc.ts'
 @ ./node_modules/eosjs/dist/index.js 21:22-48
 @ ./src/service/wax.ts 4:0-32 13:21-28 65:12-19
 @ ./src/components/Home.tsx 16:0-39 34:15-20
 @ ./src/App.tsx 6:0-37 38:39-43
 @ ./src/index.tsx 6:0-24 19:37-40

WARNING in ./node_modules/eosjs/dist/eosjs-numeric.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-numeric.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-numeric.ts'
 @ ./node_modules/eosjs/dist/index.js 30:14-40
 @ ./src/service/wax.ts 4:0-32 13:21-28 65:12-19
 @ ./src/components/Home.tsx 16:0-39 34:15-20
 @ ./src/App.tsx 6:0-37 38:39-43
 @ ./src/index.tsx 6:0-24 19:37-40

WARNING in ./node_modules/eosjs/dist/eosjs-rpc-interfaces.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-rpc-interfaces.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-rpc-interfaces.ts' @ ./node_modules/eosjs/dist/index.js 34:20-53
 @ ./src/service/wax.ts 4:0-32 13:21-28 65:12-19
 @ ./src/components/Home.tsx 16:0-39 34:15-20
 @ ./src/App.tsx 6:0-37 38:39-43
 @ ./src/index.tsx 6:0-24 19:37-40

WARNING in ./node_modules/eosjs/dist/eosjs-rpcerror.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-rpcerror.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-rpcerror.ts'
 @ ./node_modules/eosjs/dist/index.js 38:23-50
 @ ./src/service/wax.ts 4:0-32 13:21-28 65:12-19
 @ ./src/components/Home.tsx 16:0-39 34:15-20
 @ ./src/App.tsx 6:0-37 38:39-43
 @ ./src/index.tsx 6:0-24 19:37-40

WARNING in ./node_modules/eosjs/dist/eosjs-serialize.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-serialize.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\eosjs-serialize.ts'
 @ ./node_modules/eosjs/dist/index.js 47:16-44
 @ ./src/service/wax.ts 4:0-32 13:21-28 65:12-19
 @ ./src/components/Home.tsx 16:0-39 34:15-20
 @ ./src/App.tsx 6:0-37 38:39-43
 @ ./src/index.tsx 6:0-24 19:37-40

WARNING in ./node_modules/eosjs/dist/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\index.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Devos\Desktop\fw-bot-main\node_modules\eosjs\src\index.ts'
 @ ./src/service/wax.ts 4:0-32 13:21-28 65:12-19
 @ ./src/components/Home.tsx 16:0-39 34:15-20
 @ ./src/App.tsx 6:0-37 38:39-43
 @ ./src/index.tsx 6:0-24 19:37-40

8 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.72.0 compiled with 8 warnings in 1147 ms
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.

**Comment by Splash-07** [comment]
Must be fixed with last patch, try to [clear local storage](https://i.imgur.com/nVDSwKZ.png) (f12=>application=>Local Storage and delete 'presist:endpoint', 'presist:settings') and go trough installation guide again. Sorry for this issue.
